### ISSUE TITLE
Suggestions for images

### ISSUE THREAD

**Issue by jeremyphilemon** [comsocvitc/comsocvitc.github.io#5]
Robotics: https://cdn.dribbble.com/users/992274/screenshots/3915317/dribbble_kit8-net_800x600.gif

Bone Tech: https://cdn.dribbble.com/users/1129235/screenshots/4943163/main.gif

Brain Tech: https://cdn.dribbble.com/users/236204/screenshots/2921419/techno_illo_gif.gif

**Comment by vishhvak** [comment]
Changed. Thanks for the suggestions!
